# Generated by Django 2.2.2 on 2019-08-07 00:36

from django.db import migrations, models

from .. import twitch

def gen_usernames(apps, schema_editor):
    TwitchUser = apps.get_model('classic_tetris_project', 'TwitchUser')
    for twitch_user in TwitchUser.objects.all():
        twitch_user.username = twitch.client.get_user(twitch_user.twitch_id).username
        twitch_user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0003_auto_20190628_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchuser',
            name='username',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.RunPython(gen_usernames, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='twitchuser',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
