# Generated by Django 2.2.2 on 2019-08-10 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0004_twitchuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord_user', to='classic_tetris_project.User'),
        ),
        migrations.AlterField(
            model_name='twitchuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twitch_user', to='classic_tetris_project.User'),
        ),
    ]
