# Generated by Django 2.2.2 on 2019-08-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0006_auto_20190812_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins1', models.IntegerField(default=0)),
                ('wins2', models.IntegerField(default=0)),
                ('ended_at', models.DateTimeField(null=True)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='classic_tetris_project.TwitchUser')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='classic_tetris_project.User')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='classic_tetris_project.User')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('losing_score', models.IntegerField()),
                ('ended_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classic_tetris_project.Match')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classic_tetris_project.User')),
            ],
        ),
    ]
