# Generated by Django 2.2.4 on 2019-08-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0007_game_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='losing_score',
            field=models.IntegerField(null=True),
        ),
    ]
