# Generated by Django 2.2.4 on 2019-08-31 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0008_auto_20190825_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchChannel',
            fields=[
                ('twitch_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='channel', serialize=False, to='classic_tetris_project.TwitchUser')),
                ('connected', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
