# Generated by Django 2.2.4 on 2019-11-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0009_twitchchannel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'matches'},
        ),
        migrations.AddField(
            model_name='user',
            name='playstyle',
            field=models.CharField(choices=[('das', 'DAS'), ('hypertap', 'Hypertap'), ('hybrid', 'Hybrid')], max_length=16, null=True),
        ),
    ]
