# Generated by Django 2.2.4 on 2020-02-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0010_auto_20191102_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='same_piece_sets',
            field=models.BooleanField(default=False),
        ),
    ]
