# Generated by Django 2.2.4 on 2020-03-18 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0014_auto_20200313_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('output', models.CharField(max_length=400, null=True)),
                ('alias_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classic_tetris_project.CustomCommand')),
                ('twitch_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classic_tetris_project.TwitchChannel')),
            ],
        ),
        migrations.AddIndex(
            model_name='customcommand',
            index=models.Index(fields=['twitch_channel'], name='classic_tet_twitch__a83c1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='customcommand',
            constraint=models.UniqueConstraint(fields=('twitch_channel', 'name'), name='unique channel plus command'),
        ),
    ]
