# Generated by Django 2.2.4 on 2020-04-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0019_discorduser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pronouns',
            field=models.CharField(choices=[('he', 'He/him/his'), ('she', 'She/her/hers'), ('they', 'They/them/theirs')], max_length=16, null=True),
        ),
    ]
