# Generated by Django 2.2.4 on 2020-04-07 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0020_auto_20200420_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorePB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('lines', models.IntegerField(blank=True, null=True)),
                ('starting_level', models.IntegerField(blank=True, null=True)),
                ('console_type', models.CharField(choices=[('ntsc', 'NTSC'), ('pal', 'PAL')], default='ntsc', max_length=5)),
                ('current', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_pbs', related_query_name='score_pb', to='classic_tetris_project.User')),
            ],
        ),
        migrations.AddIndex(
            model_name='scorepb',
            index=models.Index(condition=models.Q(current=True), fields=['user', 'current'], name='user_current'),
        ),
        migrations.AddConstraint(
            model_name='scorepb',
            constraint=models.UniqueConstraint(condition=models.Q(current=True), fields=('user', 'starting_level', 'console_type'), name='unique_when_current'),
        ),
    ]
