# Generated by Django 2.2.4 on 2020-04-03 04:05

from django.db import migrations
from django.utils import timezone

def populate_score_pb(apps, schema_editor):
    User = apps.get_model("classic_tetris_project", "User")
    ScorePB = apps.get_model("classic_tetris_project", "ScorePB")
    now = timezone.now()
    for user in User.objects.all():
        if user.ntsc_pb:
            ScorePB.objects.create(user=user, score=user.ntsc_pb, console_type="ntsc",
                                   current=True, created_at=user.ntsc_pb_updated_at or now)
        if user.pal_pb:
            ScorePB.objects.create(user=user, score=user.pal_pb, console_type="pal",
                                   current=True, created_at=user.pal_pb_updated_at or now)
        if user.ntsc_pb_19:
            ScorePB.objects.create(user=user, score=user.ntsc_pb_19, console_type="ntsc",
                                   starting_level=19,
                                   current=True, created_at=user.ntsc_pb_19_updated_at or now)


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0021_scorepb'),
    ]

    operations = [
        migrations.RunPython(populate_score_pb, migrations.RunPython.noop),
    ]
