# Generated by Django 2.2.4 on 2020-04-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0022_populate_scorepb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ntsc_pb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ntsc_pb_19',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ntsc_pb_19_updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ntsc_pb_updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pal_pb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pal_pb_updated_at',
        ),
    ]
