# Generated by Django 2.2.10 on 2020-05-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0025_populate_discord_user_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='discriminator',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='username',
            field=models.CharField(max_length=32),
        ),
    ]
