# Generated by Django 3.1.3 on 2020-11-30 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0027_auto_20200621_0117'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customcommand',
            name='classic_tet_twitch__a83c1c_idx',
        ),
        migrations.AlterField(
            model_name='customcommand',
            name='alias_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classic_tetris_project.customcommand'),
        ),
        migrations.AlterField(
            model_name='customcommand',
            name='output',
            field=models.CharField(blank=True, default='', max_length=400),
            preserve_default=False,
        ),
    ]
