# Generated by Django 3.1.3 on 2020-12-05 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0028_auto_20201130_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcommand',
            name='alias_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classic_tetris_project.customcommand'),
        ),
    ]
