# Generated by Django 3.1.3 on 2020-12-20 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classic_tetris_project', '0030_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField()),
                ('qualifying_type', models.IntegerField(choices=[(1, 'Three Score Average')])),
                ('qualifying_open', models.BooleanField(default=False)),
                ('qualifying_instructions', markdownx.models.MarkdownxField(blank=True)),
                ('event_info', markdownx.models.MarkdownxField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifying_score', models.IntegerField()),
                ('qualifying_data', models.JSONField()),
                ('vod', models.URLField()),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=None, null=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifiers', to='classic_tetris_project.event')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classic_tetris_project.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classic_tetris_project.event')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_players', to='classic_tetris_project.tournament')),
                ('qualifier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_player', to='classic_tetris_project.qualifier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_players', to='classic_tetris_project.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='qualifier',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_user'),
        ),
    ]
