# Generated by Django 3.1.3 on 2020-12-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0031_auto_20201220_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifier',
            name='qualifying_type',
            field=models.IntegerField(choices=[(1, 'Highest Score'), (2, 'Highest 3 Scores')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='qualifying_type',
            field=models.IntegerField(choices=[(1, 'Highest Score'), (2, 'Highest 3 Scores')]),
        ),
    ]
