# Generated by Django 3.1.3 on 2021-01-25 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0033_qualifier_review_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifier',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifiers_reviewed', to='classic_tetris_project.user'),
        ),
    ]
