# Generated by Django 3.1.3 on 2021-01-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0034_auto_20210125_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifier',
            name='auth_word',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
