# Generated by Django 3.1.3 on 2021-02-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0035_qualifier_auth_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifier',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualifier',
            name='submitted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
