# Generated by Django 3.1.3 on 2021-02-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0036_auto_20210201_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifier',
            name='qualifying_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='qualifying_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='vod',
            field=models.URLField(null=True),
        ),
    ]
