# Generated by Django 3.1.3 on 2021-02-01 06:26

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0037_auto_20210201_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pre_qualifying_instructions',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
