# Generated by Django 3.1.3 on 2021-02-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0038_event_pre_qualifying_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifier',
            name='withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='qualifying_type',
            field=models.IntegerField(choices=[(1, 'Highest Score'), (2, 'Highest 2 Scores'), (3, 'Highest 3 Scores')]),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='qualifying_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='qualifying_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='qualifying_type',
            field=models.IntegerField(choices=[(1, 'Highest Score'), (2, 'Highest 2 Scores'), (3, 'Highest 3 Scores')]),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
