# Generated by Django 3.1.3 on 2021-03-27 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0039_auto_20210228_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentplayer',
            old_name='event',
            new_name='tournament',
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='qualifier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='tournament_player', to='classic_tetris_project.qualifier'),
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField()),
                ('source1_type', models.IntegerField(choices=[(1, 'None'), (2, 'Seed'), (3, 'Match Winner'), (4, 'Match Loser')])),
                ('source1_data', models.IntegerField()),
                ('source2_type', models.IntegerField(choices=[(1, 'None'), (2, 'Seed'), (3, 'Match Winner'), (4, 'Match Loser')])),
                ('source2_data', models.IntegerField()),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='classic_tetris_project.tournamentplayer')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='classic_tetris_project.tournamentplayer')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='classic_tetris_project.tournamentplayer')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classic_tetris_project.tournament')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='classic_tetris_project.tournamentplayer')),
            ],
        ),
    ]
