# Generated by Django 3.1.3 on 2021-03-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0042_auto_20210327_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='priority',
        ),
        migrations.AddField(
            model_name='tournament',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Used to order tournaments for seeding'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(blank=True, help_text='Full name of the tournament. Leave blank to automatically set to event name + short name.', max_length=64),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='seed_count',
            field=models.IntegerField(help_text='Number of players to seed into this tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(blank=True, db_index=False),
        ),
    ]
