# Generated by Django 3.1.3 on 2021-04-05 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0044_auto_20210404_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='placeholders',
            field=models.JSONField(default=dict, help_text="Reserves a seed that won't get automatically populated by a qualifier"),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='event',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='classic_tetris_project.event'),
        ),
    ]
