# Generated by Django 3.1.3 on 2021-04-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0045_auto_20210405_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='name_override',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='placeholders',
            field=models.JSONField(blank=True, default=dict, help_text="Reserves a seed that won't get automatically populated by a qualifier"),
        ),
    ]
