# Generated by Django 3.1.3 on 2021-04-17 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0047_auto_20210405_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='round_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='classic_tetris_project.tournament'),
        ),
    ]
