# Generated by Django 3.1.3 on 2021-05-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0049_auto_20210417_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='public',
            field=models.BooleanField(default=False, help_text='Controls whether the tournament page is available to view'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='restreamed',
            field=models.BooleanField(default=True),
        ),
    ]
