# Generated by Django 3.1.3 on 2021-06-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0050_auto_20210515_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='restreamed',
            field=models.BooleanField(default=False, help_text="Determines whether this tournament's matches can be restreamed by default"),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='restreamed',
            field=models.BooleanField(default=False),
        ),
    ]
