# Generated by Django 3.1.3 on 2021-06-07 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0051_auto_20210607_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='classic_tetris_project.twitchchannel'),
        ),
    ]
