# Generated by Django 3.1.3 on 2021-06-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0052_auto_20210607_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentmatch',
            options={'permissions': [('restream', 'Can schedule and report restreamed matches')]},
        ),
    ]
