# Generated by Django 3.1.3 on 2021-08-02 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0054_auto_20210802_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatch',
            name='match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classic_tetris_project.match'),
        ),
    ]
