# Generated by Django 3.1.3 on 2021-12-31 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0055_auto_20210802_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='playstyle',
            field=models.CharField(blank=True, choices=[('das', 'DAS'), ('hypertap', 'Hypertap'), ('hybrid', 'Hybrid'), ('roll', 'Roll')], max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='Restreamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restreamer', to='classic_tetris_project.user')),
            ],
        ),
    ]
