# Generated by Django 3.1.3 on 2022-01-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0056_auto_20211231_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentmatch',
            options={'permissions': [('restream', 'Can schedule and report restreamed matches')], 'verbose_name_plural': 'tournament matches'},
        ),
        migrations.AddField(
            model_name='match',
            name='vod',
            field=models.URLField(blank=True, null=True),
        ),
    ]
