# Generated by Django 3.1.3 on 2022-01-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0058_auto_20220104_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentmatch',
            options={'permissions': [('restream', 'Can report restreamable matches')], 'verbose_name_plural': 'tournament matches'},
        ),
        migrations.AddField(
            model_name='tournament',
            name='active',
            field=models.BooleanField(default=True, help_text="Controls whether this tournament's bracket should be updated on match completion"),
        ),
    ]
