# Generated by Django 3.1.3 on 2022-01-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0059_auto_20220109_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='google_sheets_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='google_sheets_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
