# Generated by Django 3.2.11 on 2022-01-31 01:18

from django.db import migrations

def update_tournament_placeholders(apps, schema_editor):
    Tournament = apps.get_model("classic_tetris_project", "Tournament")
    for tournament in Tournament.objects.all():
        if tournament.placeholders:
            for key in tournament.placeholders.keys():
                if isinstance(tournament.placeholders[key], str):
                    tournament.placeholders[key] = { "name": tournament.placeholders[key] }
            tournament.save()

class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0061_auto_20220129_2001'),
    ]

    operations = [
        migrations.RunPython(update_tournament_placeholders),
    ]
