# Generated by Django 3.2.11 on 2022-02-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0063_auto_20220131_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='discord_emote_string',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
