# Generated by Django 3.2.11 on 2022-02-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0064_tournament_discord_emote_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchuser',
            name='display_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
