# Generated by Django 3.2.11 on 2022-04-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0065_twitchuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
