# Generated by Django 3.2.11 on 2022-07-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0068_auto_20220717_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifier',
            name='vod',
            field=models.URLField(blank=True, null=True),
        ),
    ]
