# Generated by Django 3.2.11 on 2022-07-26 18:24

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0069_alter_qualifier_vod'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bracket_color',
            field=colorfield.fields.ColorField(default='#b7b7b7', max_length=18),
        ),
    ]
