# Generated by Django 3.2.11 on 2022-07-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0071_alter_tournament_bracket_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='bracket_color',
        ),
    ]
