# Generated by Django 3.2.11 on 2022-10-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0073_tournament_bracket_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qualifying_channel_id',
            field=models.CharField(blank=True, help_text='Discord channel id that qualifier announcements will be posted to. If blank, announcements will not be posted.', max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='reporting_channel_id',
            field=models.CharField(blank=True, help_text='Discord channel id that match reports will be posted to. If blank, messages will not be posted.', max_length=64),
        ),
    ]
