# Generated by Django 3.2.11 on 2023-04-29 22:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0075_auto_20230429_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True),
        ),
    ]
