# Generated by Django 3.2.11 on 2023-11-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0076_tournamentmatch_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='use_custom_font',
            field=models.BooleanField(default=False),
        ),
    ]
