# Generated by Django 3.2.11 on 2024-05-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0077_event_use_custom_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='qualifying_type',
            field=models.IntegerField(choices=[(1, 'Highest Score'), (2, 'Highest 2 Scores'), (3, 'Highest 3 Scores'), (4, 'Most Maxouts'), (5, 'Lowest Time'), (6, 'Clipped Seven Game Average')]),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='qualifying_type',
            field=models.IntegerField(choices=[(1, 'Highest Score'), (2, 'Highest 2 Scores'), (3, 'Highest 3 Scores'), (4, 'Most Maxouts'), (5, 'Lowest Time'), (6, 'Clipped Seven Game Average')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('he', 'He/him/his'), ('she', 'She/her/hers'), ('they', 'They/them/theirs'), ('it', 'It/its'), ('xe', 'Xe/xem/xir')], max_length=16, null=True),
        ),
    ]
