# Generated by Django 3.2.11 on 2025-07-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0079_alter_user_pronouns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='qualifying_type',
            field=models.IntegerField(choices=[(1, 'Highest Score'), (2, 'Highest 2 Scores'), (3, 'Highest 3 Scores'), (4, 'Most Maxouts'), (5, 'Lowest Time'), (6, 'Clipped Seven Game Average'), (7, 'CTW Format')]),
        ),
        migrations.AlterField(
            model_name='qualifier',
            name='qualifying_type',
            field=models.IntegerField(choices=[(1, 'Highest Score'), (2, 'Highest 2 Scores'), (3, 'Highest 3 Scores'), (4, 'Most Maxouts'), (5, 'Lowest Time'), (6, 'Clipped Seven Game Average'), (7, 'CTW Format')]),
        ),
    ]
