# Generated by Django 3.2.11 on 2026-04-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_tetris_project', '0080_auto_20250714_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('he', 'He/him/his'), ('she', 'She/her/hers'), ('they', 'They/them/theirs'), ('he/she', 'He/she'), ('she/he', 'She/he'), ('he/they', 'He/they'), ('they/he', 'They/he'), ('she/they', 'She/they'), ('they/she', 'They/she'), ('it', 'It/its'), ('xe', 'Xe/xem/xir'), ('any', 'Any/all'), ('ask', 'Ask')], max_length=16, null=True),
        ),
    ]
